config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get '/new_post', to: 'posts#new'
  post '/new_post', to: 'post#create'
  get '/posts', to: 'posts#index'

  root 'static_pages#home'
  get '/help', to: 'static_pages#help'

  post '/users/new', to: 'users#create'

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  resources :users
  resources :posts, only: %i[new create index]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
# frozen_string_literal: true

# Post model specifications
class Post < ApplicationRecord
  # formats the model attriutes
  validates :title, presence: true, length: { minimum: 3, maximum: 30 }
  validates :content, presence: true, length: { minimum: 10, maximum: 350 }

  # added asociation to user
  belongs_to :user
end

app/models/user.rb
# frozen_string_literal: true

# User model specifications
class User < ApplicationRecord
  # formats the email to down case before saving
  attr_accessor :rem_token
  # attr_accessor :token

  before_create :create_remember_token
  before_save { self.email = email.downcase }

  # Allows email validations for correct format
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i.freeze

  validates :username, presence: true, length: { minimum: 3, maximum: 50 }
  validates :password, presence: true, length: { minimum: 6, maximum: 255 }
  validates :email, presence: true, length: { minimum: 10, maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }

  has_secure_password
  has_many :posts

  def forget_me
    update_attribute(:remember_token, nil)
  end

  def auth(token)
    remember_token == token
  end

  def create_remember_token
    rem_token = Digest::SHA1.hexdigest(SecureRandom.urlsafe_base64)
    self.remember_token = rem_token
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  include SessionHelper
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

class PostsController < ApplicationController
  before_action :logged_in_user, only: %i[new create]

  def new
    @post = Post.new
  end

  def create
    @post = @current_user.posts.new(post_params)
    if @post.save
      flash.now[:success] = 'post created'
      redirect_to posts_path
    else
      render 'new'
    end
  end

  def index
    @posts = Post.all
  end

  def logged_in_user
    store_location
    redirect_to login_path unless logged_in?
    flash[:danger] = 'Please log in.' unless logged_in?
  end

  private

  # defines the user attributes protected
  def post_params
    params.require(:post).permit(:title, :content)
  end
end

app/controllers/sessions_controller.rb
# frozen_string_literal: true

# Actions for sessions
class SessionsController < ApplicationController
  def new; end

  def create
    user = find_user
    if user&.authenticate(params[:session][:password])
      remember user
      flash.now[:sucess] = 'Login successfull'
      redirect_to user
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end

  private

  def find_user
    User.find_by(email: params[:session][:email].downcase)
  end
end

app/controllers/static_pages_controller.rb
# frozen_string_literal: true

# Static pages controller
class StaticPagesController < ApplicationController
  def home; end

  def help; end

  def login; end

  def signup; end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

# Users controllers allows views interaction
class UsersController < ApplicationController
  before_action :set_user, only: %i[update edit destroy show]
  before_action :correct_user, only: %i[edit update]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      remember @user
      flash.now[:success] = 'The user has been created'
      redirect_to @user
    else
      render 'new'
    end
  end

  def index
    @users = User.all
  end

  def show; end

  def edit; end

  def update
    if @user.update(user_params)
      flash[:success] = 'User updated succesfully!'
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    @user.destroy
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password,
                                 :password_confirmation)
  end

  def set_user
    @user = User.find(params[:id])
  end

  # Confirms the correct user.
  def correct_user
    @user = User.find(params[:id])
    redirect_to root_url unless current_user_check(@user)
    flash[:danger] = 'Cannot edit other user!' unless current_user_check(@user)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/posts_helper.rb
# frozen_string_literal: true

module PostsHelper
end

app/helpers/session_helper.rb
# frozen_string_literal: true

# Session helper methods
module SessionHelper
  # Remembers a user in a persistent session.
  def remember(user)
    user.create_remember_token
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
    @current_user = user
  end

  def current_user
    @current_user ||= User.find_by(id: cookies.permanent.signed[:user_id]) if cookies.permanent.signed[:user_id]
  end

  def current_user_check(current_user)
    return true if session[:user_id].eql?(current_user.id)
  end

  def logged_in?
    !current_user.nil?
  end

  # Stores the URL trying to be accessed.
  def store_location
    session[:forwarding_url] = request.original_url if request.get?
  end

  def log_out
    cookies.permanent.signed[:user_id] = nil
    cookies.permanent[:remember_token] = nil
    @current_user = nil
  end
end

app/helpers/static_pages_helper.rb
# frozen_string_literal: true

module StaticPagesHelper
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "ScamBag", root_path, id: "logo", class: "navbar-brand" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Help", help_path %></li>
        <li><%= link_to "Board", posts_path %></li>
        <li><%= link_to "Sign up", new_user_path if !logged_in? %></li>
        <% if logged_in? %>
          <li><%= link_to "New Scam", new_post_path %></li>
          <li><%= link_to "Profile", current_user %></li>
          <li><%= link_to "Log out", logout_path, method: :delete %></li>
          <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_messages.html.erb
<div class="container-fluid error-messages">
    <% flash.each do |message_type, message| %>
      <div class="row">
        <div class="col-12 mt-4 alert alert-<%= message_type %>">
          <a href="#" class="close" data-dismiss="alert">&#215;</a>
          <%= message %>
        </div>
      </div>
    <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMembersOnly</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= render 'layouts/messages'%>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_with(model: post, local: true) do |f| %>

      <%= f.label :title %>
      <%= f.text_field :title, class: 'form-control margin-field' %>

      <%= f.label :content %>
      <%= f.text_area :content, class: 'form-control margin-field' %>

      <%= f.submit "Shout!", class: "btn btn-primary margin-top-4" %>
    <% end %>
  </div>
</div>

app/views/posts/create.html.erb
<h1>Posts#create</h1>
<p>Find me in app/views/posts/create.html.erb</p>

app/views/posts/index.html.erb
<div class="container posts-board">
    <% @posts.each do |post| %>
    <div class="row">
      <div class="col-lg-2">
        <img class="img-fluid rounded mb-3 mb-md-0" src="https://picsum.photos/75/75?blur" alt="">
        <h3> <%= post.user.username if logged_in? %>
            <%= 'Anonymous' if !logged_in? %>
        </h3>
      </div>
      <div class="col-lg-10">
          <h1><%= post.title %></h3>
          <p><%= post.content %></p>
      </div>
    </div>
    <br><br>
    <% end %>
</div>

app/views/posts/new.html.erb
<div class="container posts-new">
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <h1 class="italic">A new Scam, how interesting...</h1>
  </div>
</div>
  <%= render 'form', post: @post %>
</div>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/help.html.erb
<div class="container posts-board">
    <div class="row">
      <div class="col-lg-8 col-offset-2">
        <h2 class="help-title">Instructions</h2>
        <span class="line">Deprecated</span>
        <p class="help-p lead line"> It's noticeable that you are not allowed to sign up in the web interface</p>
        <p class="help-p lead mt-3 line"> No biggie, To propperly use the appication use the Rails console to create users.</p>
        <p class="help-p lead"> Web interface now allows new users to sign up, feel free to experiment in the console if that's your desire</p>
        <ul class="list-group">
            <li class="list-group-item ">Type: <span class="console-text"> rails console </span></li>
            <li class="list-group-item">Create a user using: <span class="console-text"> User.create(username: "username", email: "email", password: "password", password_confirmation: "password") </span></li>
            <li class="list-group-item">Run the server et Voila!</li>
        </ul>
        <h3>Enjoy the gossiping!</h3>
      </div>
    </div>
</div>

app/views/static_pages/home.html.erb
<div class="static-home">
  <header class="masthead">
    <div class="container h-100">
      <div class="row h-100 align-items-center">
        <div class="col-12 text-center">
          <h1 class="font-weight-light bannertext">ScamBag</h1>
          <p class="lead bannersubtext">Where you can talk BS about anyone</p>
        </div>
      </div>
    </div>
  </header>

app/views/user/new.html.erb
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user, url: signup_path) do |f| %>
    <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/_formuser.html.erb
<div class="row new_user_container">
  <div class="col-md-6 col-md-offset-3">
    <h1 class="margin-top-4">Sign up</h1>
    <%= form_for(@user, url: yield(:url)) do |f| %>
    <%= render 'shared/errors', object: @user %>

      <%= f.label :username %>
      <%= f.text_field :username, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit yield(:button_text), class: "btn btn-primary margin-top-4" %>
    <% end %>
  </div>
</div>

app/views/users/edit.html.erb
<h1>Edit user</h1>
<% provide(:button_text, 'Save changes') %>
<% provide(:url, user_path)%>
<%= render 'formuser' %>

<%= link_to "Log out", logout_path(:session), method: :delete if logged_in? %>

app/views/users/index.html.erb
<h1>User index</h1>


<%= for @users.each do |user| %>
  <p><%= user.username %></p>
<% end %>

app/views/users/new.html.erb
<% provide(:button_text, 'Create account') %>
<% provide(:url, new_user_path) %>
<%= render 'formuser' %>

app/views/users/show.html.erb
<div class="container posts-new">
  <div class="row">
    <h1>MY PROFILE</h1>
    <div class="col-lg-6">
      <img class="img-fluid rounded mb-3 mb-md-0" src="https://picsum.photos/150/150" alt="">
    </div>
    <div class="col-lg-6">
      <h1>Hello!, <%= @user.username %></h1>
      <h3>You have: <%= @user.posts.count %> Scams</h3>
    </div>
  </div>
</div>